package ui;

import oracle.jdbc.OracleDriver;
//import sun.jvm.hotspot.gc_interface.GCName;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.Year;
import java.util.*;
import java.util.Date;

/**
 * Created by Tzu-Chi Kuo on 2017/3/2.
 * IMDB Movie Query Engine
 * - Java UI
 * - Query Command
 * - Oracle DB server
 */

public class hw3 {
    /*
     * generated by GUI Designer
     */
    private JPanel MainPanel;
    private JLabel TitleLable;
    private JPanel TopPanel;
    private JPanel ButtomPanel;
    private JScrollPane GenreScrollPanel;
    private JScrollPane CountryScrollPanel;
    private JScrollPane FilmingScrollPanel;
    private JPanel CriticsPanel;
    private JPanel MovieTagPanel;
    private JPanel RatingPanel;
    private JPanel YearPanel;
    private JPanel WeightPanel;
    private JScrollPane GeneratedSQLScrollPanel;
    private JPanel SearchPanel;
    private JScrollPane ResultTableScrollPanel;
    private JPanel ConditionPanel;
    private JPanel ExecutePanel;
    private JLabel GenresLabel;
    private JLabel CountryLabel;
    private JLabel FilmingLabel;
    private JLabel OptionLabel;
    private JLabel RatingLabel;
    private JComboBox RatingComboBox;
    private JTextField RatingValueTextField;
    private JLabel RatingsLabel;
    private JLabel RatingValueLabel;
    private JComboBox WeightComboBox;
    private JTextField WeightValueTextField;
    private JLabel WeightLabel;
    private JLabel WeightValueLabel;
    private JTextArea GenerateSQLCmdTextArea;
    private JLabel GenerateSQLCmdLabel;
    private JComboBox ConditionComboBox;
    private JButton ExecuteButton;
    private JLabel SearchLabel;
    private JTable QueryResultTable;
    private JLabel QueryResultLabel;
    private JLabel MovieYearLabel;
    private JLabel YearFromLabel;
    private JLabel YearToLabel;
    private JLabel NoteLabel;
    private JPanel GenrePanel;
    private JPanel CountryPanel;
    private JPanel FilmingPanel;
    private JButton LoadButton;
    private JPanel LoadPanel;
    private JLabel FirstStepLabel;
    private JTextField YearFromTextField;
    private JComboBox ReviewComboBox;
    private JTextField ReviewValueTextField;
    private JLabel ReviewValueLabel;
    private JLabel ReviewLabel;
    private JPanel ReviewPanel;
    private JTextField YearToTextField;
    private JTextArea TagTextArea;
    private JPanel RatingReviewPanel;
    private JScrollPane TagScrollPanel;
    private JLabel TagLabel;
    private JSpinner YearToSpinner;

    /*
     * global variable
     */
    private ArrayList<JCheckBox> selectedGenres;
    private ArrayList<JCheckBox> selectedCountries;
    private ArrayList<JCheckBox> selectedFilmCountries;
    private String searchCondition;
    private Connection conn;
    private DefaultTableModel tModel;
    private String criticRating;
    private String criticValue;
    private String numOfReview;
    private String reviewValue;
    private String yearFrom;
    private String yearTo;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.setBackground(new Color(-7363092));
        MainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
        TitleLable = new JLabel();
        TitleLable.setText("Movie Query Engine");
        MainPanel.add(TitleLable, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        TopPanel = new JPanel();
        TopPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 5, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.add(TopPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        GenreScrollPanel = new JScrollPane();
        GenreScrollPanel.setHorizontalScrollBarPolicy(30);
        GenreScrollPanel.setVerticalScrollBarPolicy(20);
        TopPanel.add(GenreScrollPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(50, 100), null, 0, false));
        GenrePanel = new JPanel();
        GenrePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        GenreScrollPanel.setViewportView(GenrePanel);
        CountryScrollPanel = new JScrollPane();
        TopPanel.add(CountryScrollPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(50, 100), null, 0, false));
        CountryPanel = new JPanel();
        CountryPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        CountryScrollPanel.setViewportView(CountryPanel);
        FilmingScrollPanel = new JScrollPane();
        TopPanel.add(FilmingScrollPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(50, 100), null, 0, false));
        FilmingPanel = new JPanel();
        FilmingPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        FilmingScrollPanel.setViewportView(FilmingPanel);
        CriticsPanel = new JPanel();
        CriticsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        TopPanel.add(CriticsPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        CriticsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        YearPanel = new JPanel();
        YearPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        CriticsPanel.add(YearPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        YearPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        MovieYearLabel = new JLabel();
        MovieYearLabel.setText("Movie Year");
        YearPanel.add(MovieYearLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        YearFromLabel = new JLabel();
        YearFromLabel.setText("From");
        YearPanel.add(YearFromLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        YearToLabel = new JLabel();
        YearToLabel.setText("To:");
        YearPanel.add(YearToLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        YearFromTextField = new JTextField();
        YearPanel.add(YearFromTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        YearToTextField = new JTextField();
        YearPanel.add(YearToTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        RatingReviewPanel = new JPanel();
        RatingReviewPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        CriticsPanel.add(RatingReviewPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        RatingReviewPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        RatingPanel = new JPanel();
        RatingPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        RatingReviewPanel.add(RatingPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        RatingPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        RatingLabel = new JLabel();
        RatingLabel.setText("Critics' Rating");
        RatingPanel.add(RatingLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RatingComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("=, <, >, <=, >=");
        defaultComboBoxModel1.addElement("=");
        defaultComboBoxModel1.addElement("<");
        defaultComboBoxModel1.addElement(">");
        defaultComboBoxModel1.addElement("<=");
        defaultComboBoxModel1.addElement(">=");
        RatingComboBox.setModel(defaultComboBoxModel1);
        RatingPanel.add(RatingComboBox, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RatingValueTextField = new JTextField();
        RatingPanel.add(RatingValueTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        RatingsLabel = new JLabel();
        RatingsLabel.setText("Ratings:");
        RatingPanel.add(RatingsLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RatingValueLabel = new JLabel();
        RatingValueLabel.setText("Value:");
        RatingPanel.add(RatingValueLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ReviewPanel = new JPanel();
        ReviewPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        RatingReviewPanel.add(ReviewPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ReviewPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        ReviewComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("=, <, >, <=, >=");
        defaultComboBoxModel2.addElement("=");
        defaultComboBoxModel2.addElement("<");
        defaultComboBoxModel2.addElement(">");
        defaultComboBoxModel2.addElement("<=");
        defaultComboBoxModel2.addElement(">=");
        ReviewComboBox.setModel(defaultComboBoxModel2);
        ReviewPanel.add(ReviewComboBox, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ReviewValueTextField = new JTextField();
        ReviewPanel.add(ReviewValueTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        ReviewValueLabel = new JLabel();
        ReviewValueLabel.setText("Value:");
        ReviewPanel.add(ReviewValueLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ReviewLabel = new JLabel();
        ReviewLabel.setText("Num Of Reviews");
        ReviewPanel.add(ReviewLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MovieTagPanel = new JPanel();
        MovieTagPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        TopPanel.add(MovieTagPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MovieTagPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        WeightPanel = new JPanel();
        WeightPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        MovieTagPanel.add(WeightPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        WeightPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        WeightComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("=, <, >, <=, >=");
        defaultComboBoxModel3.addElement("=");
        defaultComboBoxModel3.addElement("<");
        defaultComboBoxModel3.addElement(">");
        defaultComboBoxModel3.addElement("<=");
        defaultComboBoxModel3.addElement(">=");
        WeightComboBox.setModel(defaultComboBoxModel3);
        WeightPanel.add(WeightComboBox, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        WeightValueTextField = new JTextField();
        WeightPanel.add(WeightValueTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 27), null, 0, false));
        WeightLabel = new JLabel();
        WeightLabel.setText("Weight:");
        WeightPanel.add(WeightLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        WeightValueLabel = new JLabel();
        WeightValueLabel.setText("Value:");
        WeightPanel.add(WeightValueLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(35, 27), null, 0, false));
        TagScrollPanel = new JScrollPane();
        MovieTagPanel.add(TagScrollPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        TagScrollPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        TagTextArea = new JTextArea();
        TagTextArea.setEditable(false);
        TagTextArea.setLineWrap(true);
        TagTextArea.setWrapStyleWord(true);
        TagScrollPanel.setViewportView(TagTextArea);
        TagLabel = new JLabel();
        TagLabel.setText("Movie Tag Value");
        MovieTagPanel.add(TagLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        GenresLabel = new JLabel();
        GenresLabel.setText("Genres");
        TopPanel.add(GenresLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CountryLabel = new JLabel();
        CountryLabel.setText("Country");
        TopPanel.add(CountryLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FilmingLabel = new JLabel();
        FilmingLabel.setText("Filming Location");
        TopPanel.add(FilmingLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        OptionLabel = new JLabel();
        OptionLabel.setText("Option");
        TopPanel.add(OptionLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtomPanel = new JPanel();
        ButtomPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.add(ButtomPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        GeneratedSQLScrollPanel = new JScrollPane();
        ButtomPanel.add(GeneratedSQLScrollPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 100), null, 0, false));
        GeneratedSQLScrollPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        GenerateSQLCmdTextArea = new JTextArea();
        GenerateSQLCmdTextArea.setEditable(false);
        GenerateSQLCmdTextArea.setLineWrap(true);
        GeneratedSQLScrollPanel.setViewportView(GenerateSQLCmdTextArea);
        SearchPanel = new JPanel();
        SearchPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        ButtomPanel.add(SearchPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        SearchPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        ConditionPanel = new JPanel();
        ConditionPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        SearchPanel.add(ConditionPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ConditionPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        ConditionComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel4 = new DefaultComboBoxModel();
        defaultComboBoxModel4.addElement("OR");
        defaultComboBoxModel4.addElement("AND");
        ConditionComboBox.setModel(defaultComboBoxModel4);
        ConditionPanel.add(ConditionComboBox, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        NoteLabel = new JLabel();
        NoteLabel.setText("Step2: Select (Default is OR)");
        ConditionPanel.add(NoteLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ExecutePanel = new JPanel();
        ExecutePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        SearchPanel.add(ExecutePanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ExecutePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        ExecuteButton = new JButton();
        ExecuteButton.setText("Execute");
        ExecutePanel.add(ExecuteButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        LoadPanel = new JPanel();
        LoadPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        SearchPanel.add(LoadPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        LoadPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        LoadButton = new JButton();
        LoadButton.setText("Load Data");
        LoadPanel.add(LoadButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FirstStepLabel = new JLabel();
        FirstStepLabel.setText("Step1: Click Load Data");
        LoadPanel.add(FirstStepLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ResultTableScrollPanel = new JScrollPane();
        ButtomPanel.add(ResultTableScrollPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(250, 100), null, 0, false));
        ResultTableScrollPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        QueryResultTable = new JTable();
        QueryResultTable.setAutoResizeMode(4);
        QueryResultTable.setFillsViewportHeight(true);
        ResultTableScrollPanel.setViewportView(QueryResultTable);
        GenerateSQLCmdLabel = new JLabel();
        GenerateSQLCmdLabel.setText("Generated SQL Command");
        ButtomPanel.add(GenerateSQLCmdLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SearchLabel = new JLabel();
        SearchLabel.setText("Search Condition");
        ButtomPanel.add(SearchLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        QueryResultLabel = new JLabel();
        QueryResultLabel.setText("Query Result");
        ButtomPanel.add(QueryResultLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }


    /*
     * attribute type
     */
    public enum AttrType {
        Genres,
        Countries
    }

    /*
     * Constructor
     *  - initialize global variables
     *  - Others: generated by GUI Designer
     *
     */
    public hw3() {
        // initialize
        conn = null;
        selectedGenres = new ArrayList<>();
        selectedCountries = new ArrayList<>();
        selectedFilmCountries = new ArrayList<>();
        searchCondition = "OR";
        // total 8 columns
        tModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                        "#", "title", "genre", "year", "country",
                        "filming locations", "AvgOfRating", "AvgOfReview"
                }
        );
        QueryResultTable.setModel(tModel);
        // set up Year range
        Calendar calendar = Calendar.getInstance();
        int curyear = calendar.get(Calendar.YEAR);
        SpinnerModel yearmodel = new SpinnerNumberModel(curyear, curyear - 100, curyear + 100, 1);
        YearToSpinner = new JSpinner(yearmodel);
        YearToSpinner.setEditor(new JSpinner.NumberEditor(YearToSpinner, "#"));

        LoadButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performLoadButton();
            }
        });
        ConditionComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performConditionComboBox(e);
            }
        });
        ExecuteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performExecuteButton();
            }
        });
        RatingComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                criticRating = RatingComboBox.getSelectedItem().toString();
                System.out.println("[Info]: Critics Selects: " + criticRating);
                performMovieTag();
            }
        });
        RatingValueTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                criticValue = RatingValueTextField.getText();
                System.out.println("[Info]: Critics Value: " + criticValue);
                performMovieTag();
            }
        });
        ReviewComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                numOfReview = ReviewComboBox.getSelectedItem().toString();
                System.out.println("[Info]: Number of Review : " + numOfReview);
                performMovieTag();
            }
        });
        ReviewValueTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                reviewValue = ReviewValueTextField.getText();
                System.out.println("[Info]: Review Value: " + reviewValue);
                performMovieTag();
            }
        });
        YearFromTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                yearFrom = YearFromTextField.getText();
                System.out.println("[Info]: Year From : " + yearFrom);
                performMovieTag();
            }
        });
        YearToTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                yearTo = YearToTextField.getText();
                System.out.println("[Info]: Year To: " + yearTo);
                performMovieTag();
            }
        });

        // TODO
        YearToSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                yearTo = String.valueOf(YearToSpinner.getValue());
                if (!yearTo.isEmpty()) {
                    System.out.println("[Info]: Year To : " + yearTo);
                    performMovieTag();
                }
            }
        });
    }

    // entry function
    public static void main(String[] args) {
        hw3 entry = new hw3();
        entry.startQueryEngine();
    }

    public void startQueryEngine() {
        // initialize UI framework
        JFrame frame = new JFrame("hw3");
        frame.setContentPane(new hw3().MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        performLoadButton();
        //while (true) ;
    }

    /*
     * Load Genre Data and reload to clean all panels
     */
    private void performLoadButton() {
        ResultSet result = null;
        // clean ui information
        removeGenrePanel();
        removeCountryPanel();
        removeFilmCountryPanel();
        removeAllText();
        RatingComboBox.setSelectedIndex(0);
        ReviewComboBox.setSelectedIndex(0);

        System.out.println("Start to load all Genres data");
        try {
            String query = "SELECT DISTINCT genre\n" + "FROM movie_genres\n" + "ORDER BY genre";
            result = executeQuery(query);
            updateGenresPanel(result);
            /*
            query = "SELECT DISTINCT country\n" + "FROM movie_countries\n";
            result = executeQuery(query);
            updateCountryPanel(result);
            */
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            closeConnect();
        }
    }

    /*
     * Performance Listener event
     */
    private void performConditionComboBox(ActionEvent e) {
        searchCondition = ConditionComboBox.getSelectedItem().toString();
        /*
        if (searchCondition == "OR") {
            loadAllCountry();
            loadAllFilmCountry();
        } else if (searchCondition == "AND") {
            loadCountry();
            loadFilmCountry();
        } */
        if (searchCondition == "OR" || searchCondition == "AND") {
            loadCountry();
            loadFilmCountry();
        } else {
            System.err.println("[Error]: Cannot find condition: " + searchCondition);
        }
    }

    /*
     * Performance Listener event
     */
    private void performExecuteButton() {
        ResultSet result = null;
        ResultSetMetaData metaresult = null;
        String query = null;
        int numOfCol = 0;
        int numOfRow = 1;

        try {
            // collect All Query request
            query = collectAllQueryRequest();
            GenerateSQLCmdTextArea.setText(query);
            result = executeQuery(query);
            metaresult = result.getMetaData();
            numOfCol = metaresult.getColumnCount();
            tModel = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                            "#", "title", "genre", "year", "country",
                            "filming locations", "AvgOfRating", "AvgOfReview"
                    }
            );
            QueryResultTable.setModel(tModel);
            // create Query result in the table
            System.out.println("Fetching data from DB server ....");
            while (result.next()) {
                Object[] objects = new Object[numOfCol + 1];
                objects[0] = numOfRow;
                for (int i = 1; i <= numOfCol; i++) {
                    objects[i] = result.getObject(i);
                }
                numOfRow++;
                tModel.addRow(objects);
            }
            if (numOfRow == 1) {
                JOptionPane.showMessageDialog(null, "No data found in DB based on the query conditions");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            closeConnect();
        }
    }

    /*
     * collect critics, review and year information to update Movie Tag
     */
    private void performMovieTag() {
        if (selectedGenres.size() != 0 && selectedCountries.size() != 0 && selectedFilmCountries.size() != 0) {
            if (!criticRating.equals("=, <, >, <=, >=")
                    && (criticValue != null)
                    && !numOfReview.equals("=, <, >, <=, >=")
                    && (reviewValue != null)
                    && (yearFrom != null) && (yearTo != null)) {
                loadMovieTag();
            }
        }
    }

    /*
     * review and return which Genre or Country JCheckbox is selected or not
     */
    private ArrayList<String> selectCheckBox(AttrType type) {
        ArrayList<String> checkList = new ArrayList<>();
        ArrayList<JCheckBox> typeList = new ArrayList<>();
        if (type.equals(AttrType.Genres)) {
            typeList = selectedGenres;
        } else if (type.equals(AttrType.Countries)) {
            typeList = selectedCountries;
        }
        for (JCheckBox cb : typeList) {
            if (cb.isSelected()) {
                checkList.add(cb.getText());
            }
        }
        return checkList;
    }

    /*
     * Create Genres JCheckBox on GenrePanel
     */
    private void updateGenresPanel(ResultSet result) throws SQLException {
        removeCountryPanel();
        removeFilmCountryPanel();
        while (result.next()) {
            GenrePanel.setLayout(new GridLayout(0, 1));
            //GenrePanel.setLayout(new GridLayout(0, 5, 20, 20));
            JCheckBox cb = new JCheckBox(result.getString(1));
            cb.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    /*
                    if (searchCondition == "OR") {
                        loadAllCountry();
                    } else if (searchCondition == "AND") {
                        loadCountry();
                    }
                    */
                    // according 3) the countries matching the genres selections will be listed
                    loadCountry();
                }
            });
            // add all queried genres JCheckbox to global variable
            selectedGenres.add(cb);
            // update GenrePanel with genres JCheckbox
            GenrePanel.add(cb);
            GenrePanel.revalidate();
            GenrePanel.repaint();
        }
        System.out.println("Load Genre completely");
    }

    /*
     * Create Country JCheckBox on CountryPanel
     */
    private void updateCountryPanel(ResultSet result) throws SQLException {
        removeCountryPanel();
        while (result.next()) {
            CountryPanel.setLayout(new GridLayout(0, 1));
            String text = result.getString(1);
            if (!text.equals(" ")) { // some genres don't have country
                JCheckBox cb = new JCheckBox(text);
                cb.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        /*
                        if (searchCondition == "OR") {
                            loadAllFilmCountry();
                        } else if (searchCondition == "AND") {
                            loadFilmCountry();
                        }
                        */
                        loadFilmCountry();
                    }
                });
                selectedCountries.add(cb);
                CountryPanel.add(cb);
                CountryPanel.revalidate();
                CountryPanel.repaint();
            }
        }
    }

    /*
     * Create Film Country JCheckBox on FilmingPanel
     */
    private void updateFilmCountryPanel(ResultSet result) throws SQLException {
        removeFilmCountryPanel();
        while (result.next()) {
            FilmingPanel.setLayout(new GridLayout(0, 1));
            String text = result.getString(1);
            if (!text.equals(" ")) { // some countries don't have filming locations
                JCheckBox cb = new JCheckBox(text);
                selectedFilmCountries.add(cb);
                FilmingPanel.add(cb);
                FilmingPanel.revalidate();
                FilmingPanel.repaint();
            }
        }
    }

    /*
     * when genre updates to non select, set GenrePanel is invisible
     */
    private void removeGenrePanel() {
        for (JCheckBox cb : selectedGenres) {
            cb.setVisible(false);
            GenrePanel.remove(cb);
        }
        // clean global list and update GenrePanel
        selectedGenres.clear();
        GenrePanel.updateUI();
    }

    /*
     * when country updates to non select, set CountryPanel is invisible
     */
    private void removeCountryPanel() {
        for (JCheckBox cb : selectedCountries) {
            cb.setVisible(false);
            CountryPanel.remove(cb);
        }
        // clean global list and update CountryPanel
        selectedCountries.clear();
        CountryPanel.updateUI();
    }

    /*
     * when filming updates to non select, set FilmingPanel is invisible
     */
    private void removeFilmCountryPanel() {
        for (JCheckBox cb : selectedFilmCountries) {
            cb.setVisible(false);
            FilmingPanel.remove(cb);
        }
        // clean global list and update FilmPanel
        selectedFilmCountries.clear();
        FilmingPanel.updateUI();
    }

    private void removeAllText() {
        RatingValueTextField.setText("");
        ReviewValueTextField.setText("");
        YearFromTextField.setText("");
        YearToTextField.setText("");
        TagTextArea.setText("");
        GenerateSQLCmdTextArea.setText("");
    }

    /*
     * Construct and return a database connection
     * throws SQL Exception if an error connection
     * throws ClassNotFoundException if DB driver not found
     */
    private Connection openConnect() throws SQLException, ClassNotFoundException {
        // Load Oracle DB driver
        DriverManager.registerDriver(new OracleDriver());
        // hard-coded configuration to connect DB server
        String host = "localhost";
        String port = "1521";
        String dbName = "xe"; // Win: xe, MAC: orcl
        String uName = "hr";
        String pWord = "hr";

        // Construct JDBC URL
        String dbURL = "jdbc:oracle:thin:@" + host + ":" + port + ":" + dbName;
        return DriverManager.getConnection(dbURL, uName, pWord);
    }

    /*
     * Close the database connection
     */
    private void closeConnect() {
        try {
            conn.close();
            System.out.println("Disconnect DB ...");
        } catch (SQLException e) {
            System.err.println("[Error]: Cannot close Oracle DB connection: " + e.getMessage());
        }
    }

    /*
     *  Query Execute function
     */
    private ResultSet executeQuery(String query) {
        Statement stmt = null;
        ResultSet result = null;
        try {
            System.out.print("Connect DB .... ");
            conn = openConnect();
            System.out.println("successfully ");
            stmt = conn.createStatement();
            result = stmt.executeQuery(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } finally {
            //closeConnect();
        }

        return result;
    }

    /*
     * For debug purpose
     */
    private void showResultSet(ResultSet result) throws SQLException {
        System.out.println("[DEBUG INFO]");
        ResultSetMetaData meta = result.getMetaData();
        //int tupleCount = 1;
        while (result.next()) {
            // System.out.print("Tuple " + tupleCount++ + " : ");
            // System.out.print("Tuple " + tupleCount++ + " : ");
            for (int col = 1; col <= meta.getColumnCount(); col++) {

                System.out.print("\"" + result.getString(col) + "\",");
            }
            System.out.println();
        }
    }

    /*
     * Collect Query Genre by referring to checkBox
     */
    private String collectQueryGenres() {
        StringBuilder sb = new StringBuilder();
        for (JCheckBox cb : selectedGenres) {
            if (cb.isSelected()) {
                if (sb.length() == 0) {
                    sb.append("(G.Genre LIKE '%" + cb.getText() + "%' ");
                } else {
                    //sb.append(searchCondition + " G.Genre LIKE '%" + cb.getText() + "%' ");
                    sb.append(searchCondition + " G.Genre LIKE '%" + cb.getText() + "%' ");
                }
            }
        }
        if (sb.length() != 0) {
            sb.append(")\n");
        }
        return sb.toString();
    }

    /*
     * Collect Query filming location country by referring to checkBox
     */
    private String collectQueryFilming() {
        StringBuilder sb = new StringBuilder();
        String prefix = " (";
        for (JCheckBox cb : selectedFilmCountries) {
            if (cb.isSelected()) {
                //sb.append(searchCondition + prefix + "L.LOC LIKE '%" + cb.getText() + "%' ");
                sb.append("AND" + prefix + "L.LOC LIKE '%" + cb.getText() + "%' ");
                prefix = " ";
            }
        }
        if (sb.length() != 0) {
            sb.append(")\n");
        }
        return sb.toString();
    }

    /*
     * Collect Query movie country by referring to checkBox
     */
    private String collectQueryCountries() {
        StringBuilder sb = new StringBuilder();
        String prefix = " (";
        for (JCheckBox cb : selectedCountries) {
            if (cb.isSelected()) {
                if (sb.length() == 0) {
                    //sb.append(searchCondition + prefix + "C.country = '" + cb.getText() + "' ");
                    sb.append("AND" + prefix + "C.country = '" + cb.getText() + "' ");
                } else {
                    // Assume one movie can be only produced by one country
                    sb.append("OR" + prefix + "C.country = '" + cb.getText() + "' ");
                }
                prefix = " ";
            }
        }
        if (sb.length() != 0) {
            sb.append(")\n");
        }
        return sb.toString();
    }

    /*
     * Collect critics rating and its value by referring to criticsRating and criticValue
     */
    private String collectQueryRating() {
        StringBuilder sb = new StringBuilder();
        if (!criticRating.equals("=, <, >, <=, >=") && (criticValue != null)) {
            sb.append("AND (M.rtAllCriticsRating " + criticRating + " " + criticValue + ")\n");
        }
        return sb.toString();
    }

    /*
     * Collect reivew and its value by referring to numOfReview and reviewValue
     */
    private String collectQueryReview() {
        StringBuilder sb = new StringBuilder();
        if (!numOfReview.equals("=, <, >, <=, >=") && reviewValue != null) {
            sb.append("AND (M.rtAllCriticsNumReviews " + numOfReview + " " + reviewValue + ")\n");
        }
        return sb.toString();
    }

    /*
     * Collect movie year by referring to yearFrom
     */
    private String collectQueryYear() {
        StringBuilder sb = new StringBuilder();
        if (yearFrom != null && yearTo != null) {
            sb.append("AND (M.year >= " + yearFrom + " AND M.year <= " + yearTo + ")\n");
        }
        return sb.toString();
    }

    /*
     * Collect Movie Tag weight by referring to weightCombox
     */
    private String collectQueryWeight() {
        StringBuilder sb = new StringBuilder();
        String weight = WeightComboBox.getSelectedItem().toString();
        String value = WeightValueTextField.getText();
        if (!weight.equals("=, <, >, <=, >=") && (value != null)) {
            sb.append("AND (MT.tagWeight " + weight + " " + value + ")\n");
        }
        return sb.toString();
    }

    /*
     * Collect All Query request from each Panel
     * Use AND to all query condition e.g. AND between genres , countries and so on
     */
    private String collectAllQueryRequest() {
        StringBuilder select = new StringBuilder();
        StringBuilder from = new StringBuilder();
        StringBuilder where = new StringBuilder();

        // set up select part
        select.append("SELECT DISTINCT title, G.genre as genre, year, C.country, L.LOC AS filmingLoc,\n");
        // use SQL to calculate average
        select.append("TRUNC((rtAllCriticsRating+rtTopCriticsRating+rtAudienceRating)/3, 2) AS AvgRating,\n");
        select.append("TRUNC((rtAllCriticsNumReviews+rtTopCriticsNumReviews+rtAudienceNumRatings)/3, 2) AS AvgReviews\n");
        // set up from part
        from.append("FROM movies M, ");
        // one movie can be more than one filming location country
        from.append("(SELECT DISTINCT movieID, LISTAGG(location1, ',') WITHIN GROUP (ORDER BY location1) AS LOC\n");
        from.append("FROM (SELECT DISTINCT location1, movieID FROM movie_locations) LOC2\n");
        from.append("GROUP BY LOC2.movieID) L, movie_countries C,\n");
        // one movie can be more than one genre
        from.append("(SELECT DISTINCT movieID, LISTAGG(genre, ', ') WITHIN GROUP (ORDER BY genre) AS Genre\n");
        from.append("FROM movie_genres GROUP BY movie_genres.movieID) G\n");
        // movie_tags and tags table
        from.append("LEFT OUTER JOIN\n");
        from.append("(SELECT DISTINCT movieID, tagWeight, value\n");
        from.append("FROM movie_tags mt, tags t\n");
        from.append("WHERE mt.tagID = t.tagID\n");
        from.append(") MT on MT.movieID = G.movieID\n");
        // set up where part
        where.append("WHERE M.movieID = G.movieID AND M.movieID = C.movieID AND ");
        where.append("G.movieID = C.movieID AND C.movieID = L.movieID ");
        // combine other query information
        if (selectedGenres.size() != 0) {
            where.append("AND (\n");
            where.append(collectQueryGenres() + collectQueryCountries() + collectQueryFilming());
            where.append(collectQueryRating() + collectQueryReview() + collectQueryYear());
            where.append(collectQueryWeight());
            where.append(")");
        }

        return select.toString() + from.toString() + where.toString();
    }

    /*
     * Update and create Country JCheckBox on GenreScrollPanel
     * OR condition
     */
    private void loadAllCountry() {
        ResultSet result = null;
        try {
            String query = "SELECT DISTINCT country\n" + "FROM movie_countries";
            result = executeQuery(query);
            updateCountryPanel(result);
            // debug purpose
            //GenerateSQLCmdTextArea.setText(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            closeConnect();
        }
    }

    /*
     * Update and create Country JCheckBox on CountryScrollPanel
     * AND/OR condition
     */
    private void loadCountry() {
        ArrayList<String> checkList = selectCheckBox(AttrType.Genres);
        ResultSet result = null;

        if (checkList.size() != 0) {
            StringBuilder sb = new StringBuilder();
            // prepare query command
            sb.append("SELECT DISTINCT country\n");
            sb.append("FROM movie_countries loc, ");
            sb.append("(");
            sb.append("SELECT movieID, LISTAGG(genre, ',') WITHIN GROUP (ORDER BY genre) AS Genres\n");
            sb.append("FROM movie_genres\n");
            sb.append("GROUP BY movieID) select_genre\n");
            sb.append("WHERE select_genre.movieID = loc.movieID AND ");
            sb.append("(");
            for (int i = 0; i < checkList.size(); i++) {
                if (i == 0) {
                    sb.append("select_genre.Genres LIKE '%" + checkList.get(i) + "%'\n");
                } else {
                    sb.append(searchCondition + " select_genre.Genres LIKE '%" + checkList.get(i) + "%'\n");
                }
            }
            sb.append(")\n");
            sb.append("ORDER BY country");
            GenerateSQLCmdTextArea.setText(sb.toString());
            // connection DB and execute query command
            try {
                result = executeQuery(sb.toString());
                updateCountryPanel(result);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            removeCountryPanel();
            removeFilmCountryPanel();
        }
    }

    /*
     * Update and create Film Country JCheckBox on FilmingScrollPanel
     * OR condition
     */
    private void loadAllFilmCountry() {
        ResultSet result = null;
        try {
            String query = "SELECT DISTINCT location1\n" + "FROM movie_locations";
            result = executeQuery(query);
            updateFilmCountryPanel(result);
            // debug purpose
            //GenerateSQLCmdTextArea.setText(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            closeConnect();
        }
    }

    /*
     * Update and create Film Country JCheckBox on FilmingScrollPanel
     * AND/OR condition in attributes
     */
    private void loadFilmCountry() {
        ArrayList<String> checkGenreList = selectCheckBox(AttrType.Genres);
        ArrayList<String> checkCountryList = selectCheckBox(AttrType.Countries);
        ResultSet result = null;

        if (checkGenreList.size() != 0 && checkCountryList.size() != 0) {
            StringBuilder sb = new StringBuilder();
            // prepare query command
            sb.append("SELECT DISTINCT location1\n");
            sb.append("FROM movie_countries cty, movie_locations loc, ");
            sb.append("(");
            sb.append("SELECT movieID, LISTAGG(genre, ',') WITHIN GROUP (ORDER BY genre) AS Genres\n");
            sb.append("FROM movie_genres\n");
            sb.append("GROUP BY movieID) select_genre\n");
            sb.append("WHERE select_genre.movieID = cty.movieID AND cty.movieID = loc.movieID AND ");
            for (int i = 0; i < checkGenreList.size(); i++) {
                if (i == 0) {
                    sb.append("(");
                    sb.append("select_genre.Genres LIKE '%" + checkGenreList.get(i) + "%'\n");
                } else {
                    sb.append(searchCondition + " select_genre.Genres LIKE '%" + checkGenreList.get(i) + "%'\n");
                }
            }
            sb.append(") ");
            sb.append("AND ");
            for (int j = 0; j < checkCountryList.size(); j++) {
                if (j == 0) {
                    sb.append("(");
                    //sb.append("cty.country LIKE '%" + checkCountryList.get(j) + "%'\n");
                    sb.append("cty.country = '" + checkCountryList.get(j) + "'\n");
                } else {
                    //sb.append(searchCondition + " cty.country LIKE '%" + checkCountryList.get(j) + "%'\n");
                    sb.append(searchCondition + " cty.country = '" + checkCountryList.get(j) + "'\n");
                }
            }
            sb.append(")\n");
            sb.append("ORDER BY location1");
            GenerateSQLCmdTextArea.setText(sb.toString());
            // connection DB and execute query command
            try {
                result = executeQuery(sb.toString());
                updateFilmCountryPanel(result);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            removeFilmCountryPanel();
        }
    }

    /*
     * Update and text Movie Tag on MovieTagTextArea
     */
    private void loadMovieTag() {
        ResultSet result = null;
        StringBuilder resultsb = new StringBuilder();
        StringBuilder sb = new StringBuilder();

        //sb.append("SELECT LISTAGG(T.value, ', ') WITHIN GROUP (ORDER BY value) AS TAGNAME\n");
        sb.append("SELECT DISTINCT T.value\n");
        sb.append("FROM movies M, movie_tags MT , tags T, ");
        // one movie can be more than one filming location country
        sb.append("(SELECT DISTINCT movieID, LISTAGG(location1, ',') WITHIN GROUP (ORDER BY location1) AS LOC\n");
        sb.append("FROM (SELECT DISTINCT location1, movieID FROM movie_locations) LOC2\n");
        sb.append("GROUP BY movieID) L, movie_countries C,\n");
        // one movie can be more than one genre
        sb.append("(SELECT movieID, LISTAGG(genre, ', ') WITHIN GROUP (ORDER BY genre) AS Genre\n");
        sb.append("FROM movie_genres GROUP BY movieID) G\n");
        // specify Movie
        sb.append("WHERE M.movieID = MT.movieID AND MT.tagID = T.tagID\n");
        // specify Rating, Review and Year condition
        sb.append("AND M.rtAllCriticsRating " + criticRating + " " + criticValue + " ");
        sb.append("AND M.rtAllCriticsNumReviews " + numOfReview + " " + reviewValue + " ");
        sb.append("AND M.year >= " + yearFrom + " AND M.year <= " + yearTo);
        sb.append("\n");
        // specify genres, countries and locations
        sb.append("AND M.movieID = G.movieID AND M.movieID = C.movieID ");
        sb.append("AND G.movieID = C.movieID AND C.movieID = L.movieID ");
        //sb.append("AND M.movieID = C.movieID AND M.movieID = G.movieID AND G.movieID = C.movieID ");
        // combine other query information
        if (selectedGenres.size() != 0) {
            sb.append("AND (\n");
            sb.append(collectQueryGenres() + collectQueryCountries() + collectQueryFilming());
            sb.append(")");
        }
        // show the query command
        GenerateSQLCmdTextArea.setText(sb.toString());
        // connection DB and execute query command
        try {
            result = executeQuery(sb.toString());
            String prefix = "";
            while (result.next()) {
                resultsb.append(prefix + result.getString(1));
                prefix = ", ";
            }
            if (resultsb.length() != 0) {
                TagTextArea.setText(resultsb.toString());
            } else {
                TagTextArea.setText("No Movie Tag can be found based on query conditions");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
